# Small example program solving problem 5.6 in Cracking the
# coding interview
# Question is to implement a function to swap all of the even numbered
# bits with all of the odd numbered bits. The problem specified to do it
# in as few operations as possible

CC = g++

CFLAG = -g -Wall -std=c++11

BitSwap: BitSwap.cpp
	clear
	$(CC) $(CFLAG) -o BitSwap BitSwap.cpp

clear:
	$(RM) BitSwap
