# Solving and testing Cracking the Coding Interview 
# Question 4.7
# Design an algorithm and write code to find the first common
# ancestor of two nodes in a binary tree. Avoid storing additional
# nodes in a data structure.
# NOTE: This is not necessarily a binary search tree

CC = g++

CFLAG = -std=c++11 -g -Wall

main: AncestorSearch.cpp TreeNode.h
	clear
	$(CC) $(CFLAG) -o AncestorSearch AncestorSearch.cpp TreeNode.h

clean:
	$(RM) AncestorSearch

