#Small makefile script for compiling code to show my answer
# to question 5.4. Only compiles 1 file into a full program
# The question is not to implement an alogorithm but to determine
# what a small piece of code does. This file does nothing but show
# my answer

CC = g++

CFLAG= -std=c++11 -g -Wall

PowerOfTwo: PowerOfTwo.cpp
	clear
	$(CC) $(CFLAG) -o PowerOfTwo PowerOfTwo.cpp

clean:
	$(RM) PowersOfTwo
